version: '3.8'
services:
  jenkins:
    build:
      context: ./
      dockerfile: ./dockerfiles/jenkins.dockerfile
      args:
        HOST_UID: 1004
        HOST_GID: 999
    env_file:
      - ./env/.env
    ports:
      - 8080:8080"
      - 50000:50000"
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
