version: '3.8'
services:
  jenkins:
    build:
      context: ./
      dockerfile: ./dockerfiles/jenkins.dockerfile
      args:
        HOST_UID: $HOST_UID
        HOST_GID: $HOST_GID
    ports:
      - $HOST_PORT:8080
      - $HOST_PORT_ANOTHER:50000
    volumes:
      - $HOST_JENKINS_DATA_VOLUME:/var/jenkins_home
      - $HOST_DOCKER_SOCK:/var/run/docker.sock
